task_name: amazon_reviews

model:
  bert_model_name: "deepset/gbert-base"
  mode: finetune

dataloader:
  num_workers: 4
  pin_memory: true
  batch_size: 4

optimizer:
  lr: 0.0000001

n_epochs: 15
save_path: "model_weights/amazon_reviews_model.pth"