task_name: chemprot

model:
  bert_model_name: "FacebookAI/roberta-base"
  mode: finetune

dataloader:
  num_workers: 4
  pin_memory: true
  batch_size: 4

optimizer:
  lr: 0.0000005

n_epochs: 15
save_path: "model_weights/chemprot_model.pth"