task_name: nubes

model:
  bert_model_name: "IIC/BETO_Galen"
  mode: finetune

dataloader:
  num_workers: 4
  pin_memory: true
  batch_size: 4

optimizer:
  lr: 0.000001

n_epochs: 50
save_path: "model_weights/nubes_model.pth"