task_name: pretrain_german_dsir_100k

mlm_probability: 0.15
text_column_name: contents

model:
  bert_model_name: "deepset/gbert-base"

dataloader:
  num_workers: 4
  pin_memory: true
  batch_size: 8

optimizer:
  lr: 0.000001

n_steps: 85000
steps_to_log: 5000
save_path: "model_weights/deepset_gbert_base_pretrained_dapt_dsir_100k.pth"