task_name: pretrain_spanish_chilean

mlm_probability: 0.15
text_column_name: text

model:
  bert_model_name: "IIC/BETO_Galen"

dataloader:
  num_workers: 4
  pin_memory: true
  batch_size: 8

optimizer:
  lr: 0.000001

n_steps: 85000
steps_to_log: 5000
save_path: "model_weights/iic_bet_galen_pretrained_dapt_chilean.pth"